### ISSUE TITLE
Read doq options for a configuration file

### ISSUE THREAD

**Issue by zubieta** [heavenshell/py-doq#93]
Several options `doq` accepts could be read from a config file like `pyproject.toml` (as described in the [PEP 518](https://www.python.org/dev/peps/pep-0518/#tool-table)) or maybe alternatively in a `.doq` file (although I personally prefer the former option) such that it is easier to call it in a consistent manner across time/machines/developers for a particular project.

A possible `pyproject.toml` would look something like this:

```toml
[tool.doq]
template_path = "./templates"
formatter = "sphinx"
style = "string"
indent = 4
ignore_exception = false
ignore_yield = false
ignore_init = false
```

I would like to ask you consider adding such feature to `doq`.

PS: Thanks for such great piece of software.
